{% set name = "torchseg" %}
{% set version = "0.0.1a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchseg-{{ version }}.tar.gz
  sha256: 4742551753599af92f9f85e5ca6b149b474ffd458bad1aad6b3aad246a3bf4ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - einops >=0.7.0
    - timm >=0.9.12
    - pytorch >=1.13

test:
  imports:
    - torchseg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/isaaccorley/torchseg
  summary: 'TorchSeg: Semantic Segmentation models for PyTorch'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamjstewart
